# Generated by Django 5.1.7 on 2025-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=20)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('eta', models.CharField(blank=True, max_length=20)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['arrival_date', 'room'],
            },
        ),
    ]
