# Generated by Django 5.1.7 on 2025-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalrecord',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
