# Generated by Django 5.1.7 on 2025-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0002_alter_arrivalrecord_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrecord',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='property_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='travel_agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
