# Generated by Django 5.1.7 on 2025-12-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0004_arrivalrecord_created_by_arrivalrecord_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrecord',
            name='first_courtesy_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='first_courtesy_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='in_house_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='second_courtesy_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='second_courtesy_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
