# Generated by Django 5.1.7 on 2025-12-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0005_arrivalrecord_first_courtesy_done_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrecord',
            name='first_courtesy_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records_first_courtesy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='in_house_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records_in_house', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='second_courtesy_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records_second_courtesy', to=settings.AUTH_USER_MODEL),
        ),
    ]
