# Generated by Django 5.1.7 on 2025-12-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0006_arrivalrecord_first_courtesy_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrecord',
            name='first_courtesy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='first_courtesy_outcome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='second_courtesy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='second_courtesy_outcome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
