# Generated by Django 5.1.7 on 2025-12-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0007_arrivalrecord_first_courtesy_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrecord',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='departed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records_departed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='departure_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='departure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='message_sent_to_guest',
            field=models.BooleanField(default=False),
        ),
    ]
