# Generated by Django 5.1.7 on 2025-12-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_experience', '0008_arrivalrecord_departed_at_arrivalrecord_departed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrecord',
            name='alert_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='last_room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='membership_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='membership_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='preference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='rate_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrivalrecord',
            name='vip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
