# Generated by Django 5.1.7 on 2025-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('EGP', 'Egyptian Pound (E£)'), ('SAR', 'Saudi Riyal (﷼)'), ('AED', 'UAE Dirham (د.إ)')], default='USD', max_length=3)),
                ('currency_symbol', models.CharField(blank=True, help_text='Custom currency symbol if needed', max_length=5)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=10)),
                ('system_name', models.CharField(default='Benchstay', max_length=100)),
                ('system_version', models.CharField(default='2.0.0', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('items_per_page', models.IntegerField(default=25, help_text='Number of items to display per page in tables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
