# Generated by Django 5.1.7 on 2025-09-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_decimal_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('view_reporting', 'Can view reporting pages'), ('view_hotelkit', 'Can view hotelkit pages'), ('view_hotel_management', 'Can view hotel management pages'), ('manage_users', 'Can manage users and roles')]},
        ),
    ]
