# Generated by Django 5.1.7 on 2025-12-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('view_reporting', 'Can view reporting pages'), ('view_hotelkit', 'Can view hotelkit pages'), ('view_hotel_management', 'Can view hotel management pages'), ('view_data_entry', 'Can view Data Entry page only'), ('manage_users', 'Can manage users and roles')]},
        ),
    ]
