# Generated by Django 4.2.20 on 2025-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Position in the original data')),
                ('id_field', models.CharField(help_text='Unique ID for the repair request', max_length=100, unique=True)),
                ('creator', models.CharField(help_text='Person who created the request', max_length=200)),
                ('recipients', models.CharField(blank=True, help_text='Recipients of the request', max_length=500, null=True)),
                ('location', models.CharField(help_text='Location where repair is needed', max_length=200)),
                ('location_path', models.CharField(blank=True, help_text='Full path to the location', max_length=500, null=True)),
                ('type', models.CharField(help_text='Type of repair request', max_length=200)),
                ('type_path', models.CharField(blank=True, help_text='Full path to the type', max_length=500, null=True)),
                ('assets', models.CharField(blank=True, help_text='Assets involved in the repair', max_length=500, null=True)),
                ('ticket', models.CharField(blank=True, help_text='Related ticket number', max_length=100, null=True)),
                ('creation_date', models.DateTimeField(help_text='When the request was created')),
                ('priority', models.CharField(blank=True, help_text='Priority level of the request', max_length=50, null=True)),
                ('state', models.CharField(help_text='Current state of the request', max_length=100)),
                ('latest_state_change_user', models.CharField(blank=True, help_text='User who made the latest state change', max_length=200, null=True)),
                ('latest_state_change_time', models.DateTimeField(blank=True, help_text='Time of the latest state change', null=True)),
                ('time_accepted', models.DateTimeField(blank=True, help_text='When the request was accepted', null=True)),
                ('time_in_progress', models.DateTimeField(blank=True, help_text='When work started', null=True)),
                ('time_done', models.DateTimeField(blank=True, help_text='When the work was completed', null=True)),
                ('time_in_evaluation', models.DateTimeField(blank=True, help_text='When the request entered evaluation', null=True)),
                ('text', models.TextField(blank=True, help_text='Description of the request', null=True)),
                ('link', models.URLField(blank=True, help_text='Related link', null=True)),
                ('submitted_result', models.TextField(blank=True, help_text='Result submitted by technician', null=True)),
                ('comments', models.TextField(blank=True, help_text='Additional comments', null=True)),
                ('parking_reason', models.TextField(blank=True, help_text='Reason for parking the request', null=True)),
                ('parking_information', models.TextField(blank=True, help_text='Additional parking information', null=True)),
                ('response_time', models.DurationField(blank=True, help_text='Time from creation to acceptance', null=True)),
                ('work_start_delay', models.DurationField(blank=True, help_text='Delay from acceptance to work start', null=True)),
                ('completion_time', models.DurationField(blank=True, help_text='Total time from creation to completion', null=True)),
                ('execution_time', models.DurationField(blank=True, help_text='Time spent on actual work', null=True)),
                ('evaluation_time', models.DurationField(blank=True, help_text='Time spent in evaluation', null=True)),
                ('latest_state_delay', models.DurationField(blank=True, help_text='Time from creation to latest state change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repair Request',
                'verbose_name_plural': 'Repair Requests',
                'ordering': ['-creation_date'],
            },
        ),
    ]
