# Generated by Django 5.1.7 on 2025-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('creator', models.CharField(max_length=255)),
                ('recipients', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField()),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('time_accepted', models.DateTimeField(blank=True, null=True)),
                ('time_done', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('completion_time', models.DurationField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
