# Generated by Django 5.1.7 on 2025-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelkit', '0002_guestrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='assets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='latest_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='latest_state_change_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='location_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='submitted_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='time_in_evaluation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='time_in_progress',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='type_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
