# Generated by Django 5.1.7 on 2025-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0002_alter_competitordata_options_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitordata',
            name='rooms_sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitordata',
            name='estimated_occupancy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]