# Generated by Django 5.1.7 on 2025-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0004_competitor_is_deleted_competitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
