# Generated by Django 5.1.7 on 2025-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0011_populate_total_rooms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitordata',
            name='adr_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='competitordata',
            name='occupancy_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='competitordata',
            name='revenue_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
