# Generated by Django 5.1.7 on 2025-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0012_competitordata_adr_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_logos/'),
        ),
    ]
