# Generated by Django 5.1.7 on 2025-08-25 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0014_update_total_revenue_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarter', 'Quarter'), ('monthly', 'Monthly')], default='annual', max_length=16)),
                ('period_detail', models.CharField(blank=True, default='', max_length=16)),
                ('occupancy_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adr_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revpar_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_revenue_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mpi_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ari_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rgi_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('lock_targets', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_goals', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to='hotel_management.hotel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_year', 'period_type', 'period_detail'],
                'unique_together': {('hotel', 'fiscal_year', 'period_type', 'period_detail')},
            },
        ),
    ]
