# Generated by Django 4.2.20 on 2025-08-27 09:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_management', '0015_budgetgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarter', 'Quarterly'), ('monthly', 'Monthly')], default='monthly', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_versions', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_versions', to='hotel_management.hotel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_year', 'name'],
                'unique_together': {('hotel', 'name', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='hotel_management.hotel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hotel_management.budgetcategory')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BudgetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approvals', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hotel_management.budgetversion')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense'), ('other', 'Other')], default='revenue', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='hotel_management.budgetcategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_accounts', to='hotel_management.hotel')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_detail', models.CharField(blank=True, default='', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='hotel_management.budgetaccount')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='hotel_management.budgetversion')),
            ],
            options={
                'ordering': ['account__code', 'period_detail'],
                'unique_together': {('version', 'account', 'period_detail')},
            },
        ),
        migrations.CreateModel(
            name='BudgetAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='hotel_management.budgetversion')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('version', 'key')},
            },
        ),
    ]
