# Generated by Django 5.1.7 on 2025-09-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0016_budgetversion_budgetcategory_budgetapproval_and_more'),
    ]

    operations = [
        # Drop unique constraints before removing fields they might reference
        migrations.AlterUniqueTogether(
            name='budgetassumption',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='budgetlineitem',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='budgetversion',
            unique_together=None,
        ),
        # Now remove fields
        migrations.RemoveField(
            model_name='budgetlineitem',
            name='account',
        ),
        migrations.RemoveField(
            model_name='budgetapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='budgetapproval',
            name='version',
        ),
        migrations.RemoveField(
            model_name='budgetassumption',
            name='version',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='budgetlineitem',
            name='version',
        ),
        migrations.RemoveField(
            model_name='budgetversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budgetversion',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='budgetversion',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='BudgetAccount',
        ),
        migrations.DeleteModel(
            name='BudgetApproval',
        ),
        migrations.DeleteModel(
            name='BudgetAssumption',
        ),
        migrations.DeleteModel(
            name='BudgetCategory',
        ),
        migrations.DeleteModel(
            name='BudgetLineItem',
        ),
        migrations.DeleteModel(
            name='BudgetVersion',
        ),
    ]
